[I 2024-12-04 14:50:59,570] A new study created in RDB with name: Omega_xgb
[I 2024-12-04 14:51:05,416] Trial 1 finished with value: 0.6607700883562138 and parameters: {'n_estimators': 1425, 'max_depth': 3, 'learning_rate': 0.05925504200196537, 'subsample': 0.8883417187083704, 'colsample_bytree': 0.8625993146610664, 'min_child_weight': 3, 'gamma': 1.4067688329622858e-05, 'reg_alpha': 0.034184280318371466, 'reg_lambda': 9.346873702244021e-05}. Best is trial 1 with value: 0.6607700883562138.
[I 2024-12-04 14:51:06,030] Trial 23 finished with value: 0.5714113158581481 and parameters: {'n_estimators': 1349, 'max_depth': 12, 'learning_rate': 0.09899803196852407, 'subsample': 0.7837595545944266, 'colsample_bytree': 0.9328792648134003, 'min_child_weight': 1, 'gamma': 0.002962040104417951, 'reg_alpha': 0.00015417377827342603, 'reg_lambda': 0.0005672742032981819}. Best is trial 13 with value: 0.5415286675109281.
[I 2024-12-04 14:51:06,054] Trial 6 finished with value: 0.5899454096503438 and parameters: {'n_estimators': 885, 'max_depth': 7, 'learning_rate': 0.011973191101962979, 'subsample': 0.8833221845210643, 'colsample_bytree': 0.7681268247044533, 'min_child_weight': 4, 'gamma': 0.0005788435320311123, 'reg_alpha': 0.041743718283459526, 'reg_lambda': 0.03697674351439062}. Best is trial 13 with value: 0.5415286675109281.
[I 2024-12-04 14:51:06,492] Trial 13 finished with value: 0.5415286675109281 and parameters: {'n_estimators': 1379, 'max_depth': 8, 'learning_rate': 0.01880852982523645, 'subsample': 0.7227745311180854, 'colsample_bytree': 0.8397358785004799, 'min_child_weight': 1, 'gamma': 0.0021897515849071867, 'reg_alpha': 0.050635625176907215, 'reg_lambda': 5.94711357388134e-05}. Best is trial 13 with value: 0.5415286675109281.
[I 2024-12-04 14:51:06,692] Trial 11 finished with value: 0.5801776218901323 and parameters: {'n_estimators': 455, 'max_depth': 11, 'learning_rate': 0.03926181895156294, 'subsample': 0.7438380219371391, 'colsample_bytree': 0.8891660655687091, 'min_child_weight': 5, 'gamma': 0.050985226557648367, 'reg_alpha': 0.007259760999070785, 'reg_lambda': 0.017407182156618108}. Best is trial 13 with value: 0.5415286675109281.
[I 2024-12-04 14:51:07,361] Trial 12 finished with value: 0.5814545087967274 and parameters: {'n_estimators': 1291, 'max_depth': 7, 'learning_rate': 0.05308118363670693, 'subsample': 0.9026769631927505, 'colsample_bytree': 0.5742369881491707, 'min_child_weight': 5, 'gamma': 1.6781921408740943e-05, 'reg_alpha': 0.0005770986331954404, 'reg_lambda': 0.0006199065803782505}. Best is trial 13 with value: 0.5415286675109281.
[I 2024-12-04 14:51:07,400] Trial 3 finished with value: 0.622877542473653 and parameters: {'n_estimators': 219, 'max_depth': 3, 'learning_rate': 0.010336426496982467, 'subsample': 0.7682750100584161, 'colsample_bytree': 0.733519725320769, 'min_child_weight': 3, 'gamma': 0.1951787840461348, 'reg_alpha': 2.9057662695178423e-05, 'reg_lambda': 8.472707310992643e-05}. Best is trial 13 with value: 0.5415286675109281.
[I 2024-12-04 14:51:07,597] Trial 14 finished with value: 0.6457500724091364 and parameters: {'n_estimators': 1092, 'max_depth': 3, 'learning_rate': 0.014416837564371754, 'subsample': 0.9202830141417517, 'colsample_bytree': 0.7900042518501558, 'min_child_weight': 2, 'gamma': 0.007199334144375342, 'reg_alpha': 0.0009303002382759077, 'reg_lambda': 1.0084446993517541e-05}. Best is trial 13 with value: 0.5415286675109281.
[I 2024-12-04 14:51:07,886] Trial 19 finished with value: 0.573897292284142 and parameters: {'n_estimators': 1359, 'max_depth': 12, 'learning_rate': 0.027976190495394775, 'subsample': 0.831004066218724, 'colsample_bytree': 0.8026112412533849, 'min_child_weight': 4, 'gamma': 0.23117309058147878, 'reg_alpha': 0.004616373988165386, 'reg_lambda': 0.4694796678983119}. Best is trial 13 with value: 0.5415286675109281.
[I 2024-12-04 14:51:08,867] Trial 10 finished with value: 0.6036740358402035 and parameters: {'n_estimators': 840, 'max_depth': 3, 'learning_rate': 0.017705946035338947, 'subsample': 0.9339062058337263, 'colsample_bytree': 0.6392987397430067, 'min_child_weight': 2, 'gamma': 0.17297363462384704, 'reg_alpha': 0.24304402367194378, 'reg_lambda': 0.3052526643883553}. Best is trial 20 with value: 0.5372368391972848.
[I 2024-12-04 14:51:09,110] Trial 15 finished with value: 0.6839304488818655 and parameters: {'n_estimators': 1475, 'max_depth': 11, 'learning_rate': 0.07211122641556628, 'subsample': 0.7112652259026333, 'colsample_bytree': 0.9609784659083904, 'min_child_weight': 2, 'gamma': 0.013384276047970862, 'reg_alpha': 0.00015448832391160364, 'reg_lambda': 0.00020755042645133326}. Best is trial 22 with value: 0.5260212170998007.
[I 2024-12-04 14:51:09,122] Trial 20 finished with value: 0.5372368391972848 and parameters: {'n_estimators': 1442, 'max_depth': 5, 'learning_rate': 0.03586834594712167, 'subsample': 0.8915656558015859, 'colsample_bytree': 0.8447727114628094, 'min_child_weight': 1, 'gamma': 0.00014512652923212468, 'reg_alpha': 0.004605818010719334, 'reg_lambda': 0.00830194458946952}. Best is trial 22 with value: 0.5260212170998007.
[I 2024-12-04 14:51:09,441] Trial 16 finished with value: 0.5610900322321964 and parameters: {'n_estimators': 534, 'max_depth': 6, 'learning_rate': 0.029420860953924183, 'subsample': 0.7406641684252102, 'colsample_bytree': 0.6036228103464267, 'min_child_weight': 4, 'gamma': 0.10133469092712874, 'reg_alpha': 0.06096008739965177, 'reg_lambda': 0.09638671446248633}. Best is trial 22 with value: 0.5260212170998007.
[I 2024-12-04 14:51:09,525] Trial 22 finished with value: 0.5260212170998007 and parameters: {'n_estimators': 825, 'max_depth': 9, 'learning_rate': 0.0911360858114139, 'subsample': 0.9309973354406043, 'colsample_bytree': 0.5875557778126664, 'min_child_weight': 1, 'gamma': 8.175828838814812e-05, 'reg_alpha': 0.0012082175205740367, 'reg_lambda': 0.0003461904223419738}. Best is trial 22 with value: 0.5260212170998007.
[I 2024-12-04 14:51:09,551] Trial 5 finished with value: 0.57687760787438 and parameters: {'n_estimators': 1359, 'max_depth': 5, 'learning_rate': 0.03652677713375843, 'subsample': 0.9433277393538226, 'colsample_bytree': 0.5641608294115781, 'min_child_weight': 5, 'gamma': 7.749486918069061e-05, 'reg_alpha': 0.00010143167258166927, 'reg_lambda': 0.0004068459832935154}. Best is trial 22 with value: 0.5260212170998007.
[I 2024-12-04 14:51:09,689] Trial 2 finished with value: 0.6321940406580504 and parameters: {'n_estimators': 1335, 'max_depth': 11, 'learning_rate': 0.06870663315454038, 'subsample': 0.9285903575859873, 'colsample_bytree': 0.5836229072431981, 'min_child_weight': 3, 'gamma': 0.005562123087295989, 'reg_alpha': 2.293773736034961e-05, 'reg_lambda': 0.0006392834145161831}. Best is trial 22 with value: 0.5260212170998007.
[I 2024-12-04 14:51:09,856] Trial 9 finished with value: 0.6436397770663578 and parameters: {'n_estimators': 1183, 'max_depth': 5, 'learning_rate': 0.09273181689712479, 'subsample': 0.7904758139797503, 'colsample_bytree': 0.5864645536423618, 'min_child_weight': 4, 'gamma': 1.5579889534003332e-05, 'reg_alpha': 0.00017651638683278574, 'reg_lambda': 0.008218726426631177}. Best is trial 22 with value: 0.5260212170998007.
[I 2024-12-04 14:51:09,880] Trial 21 finished with value: 0.6527590345884927 and parameters: {'n_estimators': 1365, 'max_depth': 11, 'learning_rate': 0.03545775092446497, 'subsample': 0.8224759858509136, 'colsample_bytree': 0.789226512108189, 'min_child_weight': 3, 'gamma': 0.004226945939369293, 'reg_alpha': 0.01624439274844669, 'reg_lambda': 0.0002472229503933091}. Best is trial 22 with value: 0.5260212170998007.
[I 2024-12-04 14:51:10,384] Trial 28 finished with value: 0.5950111787155961 and parameters: {'n_estimators': 919, 'max_depth': 7, 'learning_rate': 0.09016536218974854, 'subsample': 0.9213638962661885, 'colsample_bytree': 0.9421068347845067, 'min_child_weight': 4, 'gamma': 0.15336958368018985, 'reg_alpha': 0.12077288270639344, 'reg_lambda': 0.009547905826642158}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:10,453] Trial 0 finished with value: 0.5820215748086364 and parameters: {'n_estimators': 680, 'max_depth': 7, 'learning_rate': 0.01974396267449214, 'subsample': 0.9134218987152001, 'colsample_bytree': 0.9946952754285434, 'min_child_weight': 1, 'gamma': 0.22005974487129554, 'reg_alpha': 0.0001450603708345547, 'reg_lambda': 0.00986380198944377}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:10,463] Trial 17 finished with value: 0.6082018503194737 and parameters: {'n_estimators': 1488, 'max_depth': 6, 'learning_rate': 0.012674736928701358, 'subsample': 0.7921762163842577, 'colsample_bytree': 0.701793476944192, 'min_child_weight': 3, 'gamma': 0.05729396774015284, 'reg_alpha': 0.027012878387620655, 'reg_lambda': 0.0007760268870342336}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:10,525] Trial 25 finished with value: 0.5166598487363987 and parameters: {'n_estimators': 926, 'max_depth': 6, 'learning_rate': 0.01779280868891963, 'subsample': 0.834093203315972, 'colsample_bytree': 0.7398466187872528, 'min_child_weight': 1, 'gamma': 0.06561722812865957, 'reg_alpha': 0.027591881567680183, 'reg_lambda': 0.023566327714601213}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:10,561] Trial 4 finished with value: 0.6017182506425122 and parameters: {'n_estimators': 1108, 'max_depth': 3, 'learning_rate': 0.017397705380866147, 'subsample': 0.9571294069418985, 'colsample_bytree': 0.691241637986862, 'min_child_weight': 3, 'gamma': 0.034304317459179424, 'reg_alpha': 6.183681022527317e-05, 'reg_lambda': 0.040091998093407286}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:10,562] Trial 7 finished with value: 0.5585763205620312 and parameters: {'n_estimators': 1180, 'max_depth': 7, 'learning_rate': 0.031682867349533045, 'subsample': 0.9031719546790036, 'colsample_bytree': 0.9655925068271538, 'min_child_weight': 1, 'gamma': 0.14983216363618962, 'reg_alpha': 0.004992265537833743, 'reg_lambda': 0.010094615826631374}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:11,094] Trial 18 finished with value: 0.5310255467180032 and parameters: {'n_estimators': 997, 'max_depth': 4, 'learning_rate': 0.013713947968576484, 'subsample': 0.8138323913305273, 'colsample_bytree': 0.6706693140727968, 'min_child_weight': 1, 'gamma': 0.008054722676757877, 'reg_alpha': 2.7640895274695303e-05, 'reg_lambda': 4.7193726686435114e-05}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:11,727] Trial 30 finished with value: 0.6041644527310244 and parameters: {'n_estimators': 1286, 'max_depth': 7, 'learning_rate': 0.035260991783984695, 'subsample': 0.8784317306217713, 'colsample_bytree': 0.579137220672115, 'min_child_weight': 4, 'gamma': 0.0014507227472748492, 'reg_alpha': 0.13154466523593736, 'reg_lambda': 0.027822260577479427}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:11,880] Trial 26 finished with value: 0.5701556371822333 and parameters: {'n_estimators': 655, 'max_depth': 8, 'learning_rate': 0.011232229607680012, 'subsample': 0.9499629139863659, 'colsample_bytree': 0.6296253021768857, 'min_child_weight': 5, 'gamma': 5.5581862149337526e-05, 'reg_alpha': 0.0008900452696093889, 'reg_lambda': 0.00041201802327214815}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:12,635] Trial 27 finished with value: 0.6813942944744252 and parameters: {'n_estimators': 986, 'max_depth': 7, 'learning_rate': 0.01972288420072289, 'subsample': 0.9708987849242747, 'colsample_bytree': 0.7935922525037531, 'min_child_weight': 2, 'gamma': 7.945857468079824e-05, 'reg_alpha': 0.00012297839645008095, 'reg_lambda': 0.0016139685170885622}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:12,863] Trial 31 finished with value: 0.5863939801872889 and parameters: {'n_estimators': 816, 'max_depth': 5, 'learning_rate': 0.010957317738997276, 'subsample': 0.9819511749668793, 'colsample_bytree': 0.6987813942334022, 'min_child_weight': 3, 'gamma': 0.00034696192076275593, 'reg_alpha': 0.0019583722683760756, 'reg_lambda': 0.04628395800496836}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:13,106] Trial 8 finished with value: 0.6805675539032062 and parameters: {'n_estimators': 1138, 'max_depth': 7, 'learning_rate': 0.04498954462802708, 'subsample': 0.7254865127626597, 'colsample_bytree': 0.7919160136412827, 'min_child_weight': 3, 'gamma': 0.0004576628005704004, 'reg_alpha': 0.00028295906732320555, 'reg_lambda': 0.007453135386321826}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:13,175] Trial 29 finished with value: 0.5544690894160824 and parameters: {'n_estimators': 429, 'max_depth': 3, 'learning_rate': 0.015229386623330978, 'subsample': 0.7869025394388475, 'colsample_bytree': 0.5072055873088179, 'min_child_weight': 4, 'gamma': 0.001100539093995031, 'reg_alpha': 0.008502584427118525, 'reg_lambda': 0.30115487269400887}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:14,839] Trial 24 finished with value: 0.6691876803754047 and parameters: {'n_estimators': 464, 'max_depth': 10, 'learning_rate': 0.060499680033976586, 'subsample': 0.7769135329596286, 'colsample_bytree': 0.6441843221751598, 'min_child_weight': 2, 'gamma': 0.00022029480664430333, 'reg_alpha': 0.00026727442002673406, 'reg_lambda': 0.06903745364426743}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:31,773] Trial 32 finished with value: 0.5377208109625234 and parameters: {'n_estimators': 886, 'max_depth': 6, 'learning_rate': 0.021449466544944038, 'subsample': 0.9183622158216787, 'colsample_bytree': 0.5, 'min_child_weight': 1, 'gamma': 1.123454182238709e-05, 'reg_alpha': 0.3572770871218132, 'reg_lambda': 0.0014012022446065477}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:32,462] Trial 34 finished with value: 0.5447671349146873 and parameters: {'n_estimators': 801, 'max_depth': 7, 'learning_rate': 0.022860218867104563, 'subsample': 0.9304404530446306, 'colsample_bytree': 0.5, 'min_child_weight': 1, 'gamma': 5.7026466878098755e-05, 'reg_alpha': 0.4999999999999991, 'reg_lambda': 0.0017288339354396094}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:33,144] Trial 42 finished with value: 0.5633473680647243 and parameters: {'n_estimators': 1361, 'max_depth': 3, 'learning_rate': 0.028209052878521424, 'subsample': 0.8862381465583492, 'colsample_bytree': 0.5171199204535564, 'min_child_weight': 1, 'gamma': 0.05218587588412741, 'reg_alpha': 0.5, 'reg_lambda': 0.01348398140482683}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:34,421] Trial 37 finished with value: 0.543502120299235 and parameters: {'n_estimators': 1420, 'max_depth': 4, 'learning_rate': 0.021559374238130296, 'subsample': 0.8611160763434308, 'colsample_bytree': 0.5460438556610967, 'min_child_weight': 1, 'gamma': 0.013637469375049012, 'reg_alpha': 0.3314957390045225, 'reg_lambda': 0.033610501270734935}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:35,060] Trial 44 finished with value: 0.5525055992015455 and parameters: {'n_estimators': 1381, 'max_depth': 4, 'learning_rate': 0.02063302590048179, 'subsample': 0.9180029810561758, 'colsample_bytree': 0.5175367624676089, 'min_child_weight': 1, 'gamma': 0.03835680387333197, 'reg_alpha': 0.5, 'reg_lambda': 0.02250546299663952}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:35,127] Trial 36 finished with value: 0.5444648248049571 and parameters: {'n_estimators': 1405, 'max_depth': 4, 'learning_rate': 0.022147183372356518, 'subsample': 0.8720087019021795, 'colsample_bytree': 0.553329141995758, 'min_child_weight': 1, 'gamma': 0.012835112875781788, 'reg_alpha': 0.2957042397035442, 'reg_lambda': 0.044402441185205185}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:35,324] Trial 56 finished with value: 0.5595644894807477 and parameters: {'n_estimators': 1339, 'max_depth': 3, 'learning_rate': 0.02753827537096348, 'subsample': 0.8841069619991342, 'colsample_bytree': 0.5403382523717538, 'min_child_weight': 1, 'gamma': 0.04709833856624101, 'reg_alpha': 0.5, 'reg_lambda': 0.004743220125238651}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:35,496] Trial 38 finished with value: 0.545213392953072 and parameters: {'n_estimators': 1405, 'max_depth': 4, 'learning_rate': 0.02214339739633801, 'subsample': 0.8722004889926017, 'colsample_bytree': 0.5532560672855507, 'min_child_weight': 1, 'gamma': 0.012916132195295816, 'reg_alpha': 0.29786217352103456, 'reg_lambda': 0.04445861108353057}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:35,621] Trial 51 finished with value: 0.5595644894807477 and parameters: {'n_estimators': 1339, 'max_depth': 3, 'learning_rate': 0.02753827537096348, 'subsample': 0.8841069619991342, 'colsample_bytree': 0.5403382523717538, 'min_child_weight': 1, 'gamma': 0.04709833856624101, 'reg_alpha': 0.5, 'reg_lambda': 0.004743220125238651}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:37,395] Trial 35 finished with value: 0.5523773470558244 and parameters: {'n_estimators': 1381, 'max_depth': 4, 'learning_rate': 0.02063314817790687, 'subsample': 0.9179935013620264, 'colsample_bytree': 0.5175058998349096, 'min_child_weight': 1, 'gamma': 0.03834458387237227, 'reg_alpha': 0.5, 'reg_lambda': 0.022513263094781466}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:37,657] Trial 39 finished with value: 0.5463996637848031 and parameters: {'n_estimators': 1420, 'max_depth': 4, 'learning_rate': 0.021559600248208834, 'subsample': 0.8612226698260466, 'colsample_bytree': 0.5460313520776442, 'min_child_weight': 1, 'gamma': 0.013678956681230623, 'reg_alpha': 0.3344422115811975, 'reg_lambda': 0.033552485077141134}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:37,690] Trial 40 finished with value: 0.5482269743573686 and parameters: {'n_estimators': 1420, 'max_depth': 4, 'learning_rate': 0.02156181816842625, 'subsample': 0.8611680621989551, 'colsample_bytree': 0.5460225623931757, 'min_child_weight': 1, 'gamma': 0.01365418870520831, 'reg_alpha': 0.33567503078690675, 'reg_lambda': 0.03340131130452876}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:38,026] Trial 50 finished with value: 0.5595644894807477 and parameters: {'n_estimators': 1339, 'max_depth': 3, 'learning_rate': 0.02753827537096348, 'subsample': 0.8841069619991342, 'colsample_bytree': 0.5403382523717538, 'min_child_weight': 1, 'gamma': 0.04709833856624101, 'reg_alpha': 0.5, 'reg_lambda': 0.004743220125238651}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:38,519] Trial 52 finished with value: 0.5595644894807477 and parameters: {'n_estimators': 1339, 'max_depth': 3, 'learning_rate': 0.02753827537096348, 'subsample': 0.8841069619991342, 'colsample_bytree': 0.5403382523717538, 'min_child_weight': 1, 'gamma': 0.04709833856624101, 'reg_alpha': 0.5, 'reg_lambda': 0.004743220125238651}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:38,764] Trial 45 finished with value: 0.55313300200132 and parameters: {'n_estimators': 1381, 'max_depth': 4, 'learning_rate': 0.020636154660803797, 'subsample': 0.9179742051010552, 'colsample_bytree': 0.517586453541221, 'min_child_weight': 1, 'gamma': 0.038400867588976255, 'reg_alpha': 0.5, 'reg_lambda': 0.02248874473493381}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:38,839] Trial 41 finished with value: 0.5595644894807477 and parameters: {'n_estimators': 1339, 'max_depth': 3, 'learning_rate': 0.02753827537096348, 'subsample': 0.8841069619991342, 'colsample_bytree': 0.5403382523717538, 'min_child_weight': 1, 'gamma': 0.04709833856624101, 'reg_alpha': 0.5, 'reg_lambda': 0.004743220125238651}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:40,095] Trial 46 finished with value: 0.5595644894807477 and parameters: {'n_estimators': 1339, 'max_depth': 3, 'learning_rate': 0.02753827537096348, 'subsample': 0.8841069619991342, 'colsample_bytree': 0.5403382523717538, 'min_child_weight': 1, 'gamma': 0.04709833856624101, 'reg_alpha': 0.5, 'reg_lambda': 0.004743220125238651}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:40,419] Trial 60 finished with value: 0.5595644894807477 and parameters: {'n_estimators': 1339, 'max_depth': 3, 'learning_rate': 0.02753827537096348, 'subsample': 0.8841069619991342, 'colsample_bytree': 0.5403382523717538, 'min_child_weight': 1, 'gamma': 0.04709833856624101, 'reg_alpha': 0.5, 'reg_lambda': 0.004743220125238651}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:40,663] Trial 55 finished with value: 0.5595644894807477 and parameters: {'n_estimators': 1339, 'max_depth': 3, 'learning_rate': 0.02753827537096348, 'subsample': 0.8841069619991342, 'colsample_bytree': 0.5403382523717538, 'min_child_weight': 1, 'gamma': 0.04709833856624101, 'reg_alpha': 0.5, 'reg_lambda': 0.004743220125238651}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:40,671] Trial 62 finished with value: 0.5595644894807477 and parameters: {'n_estimators': 1339, 'max_depth': 3, 'learning_rate': 0.02753827537096348, 'subsample': 0.8841069619991342, 'colsample_bytree': 0.5403382523717538, 'min_child_weight': 1, 'gamma': 0.04709833856624101, 'reg_alpha': 0.5, 'reg_lambda': 0.004743220125238651}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:40,921] Trial 33 finished with value: 0.5455846594343248 and parameters: {'n_estimators': 1456, 'max_depth': 7, 'learning_rate': 0.011348716808826419, 'subsample': 0.8281210859737113, 'colsample_bytree': 0.729949786555177, 'min_child_weight': 1, 'gamma': 2.541990339415524e-05, 'reg_alpha': 0.5, 'reg_lambda': 0.01935731937050443}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:40,930] Trial 53 finished with value: 0.5592106301938398 and parameters: {'n_estimators': 1339, 'max_depth': 3, 'learning_rate': 0.027538536016923177, 'subsample': 0.8841545729744801, 'colsample_bytree': 0.5402465114458935, 'min_child_weight': 1, 'gamma': 0.04712453779092127, 'reg_alpha': 0.5, 'reg_lambda': 0.004729958330095781}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:40,983] Trial 47 finished with value: 0.5595644894807477 and parameters: {'n_estimators': 1339, 'max_depth': 3, 'learning_rate': 0.02753827537096348, 'subsample': 0.8841069619991342, 'colsample_bytree': 0.5403382523717538, 'min_child_weight': 1, 'gamma': 0.04709833856624101, 'reg_alpha': 0.5, 'reg_lambda': 0.004743220125238651}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:41,371] Trial 57 finished with value: 0.5595644894807477 and parameters: {'n_estimators': 1339, 'max_depth': 3, 'learning_rate': 0.02753827537096348, 'subsample': 0.8841069619991342, 'colsample_bytree': 0.5403382523717538, 'min_child_weight': 1, 'gamma': 0.04709833856624101, 'reg_alpha': 0.5, 'reg_lambda': 0.004743220125238651}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:41,419] Trial 59 finished with value: 0.5595644894807477 and parameters: {'n_estimators': 1339, 'max_depth': 3, 'learning_rate': 0.02753827537096348, 'subsample': 0.8841069619991342, 'colsample_bytree': 0.5403382523717538, 'min_child_weight': 1, 'gamma': 0.04709833856624101, 'reg_alpha': 0.5, 'reg_lambda': 0.004743220125238651}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:41,430] Trial 48 finished with value: 0.5661617938184456 and parameters: {'n_estimators': 1351, 'max_depth': 3, 'learning_rate': 0.02390658559614066, 'subsample': 0.88617032262404, 'colsample_bytree': 0.5307316829993844, 'min_child_weight': 1, 'gamma': 0.06260335366052512, 'reg_alpha': 0.5, 'reg_lambda': 0.005107232213581871}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:41,441] Trial 61 finished with value: 0.5595644894807477 and parameters: {'n_estimators': 1339, 'max_depth': 3, 'learning_rate': 0.02753827537096348, 'subsample': 0.8841069619991342, 'colsample_bytree': 0.5403382523717538, 'min_child_weight': 1, 'gamma': 0.04709833856624101, 'reg_alpha': 0.5, 'reg_lambda': 0.004743220125238651}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:41,980] Trial 54 finished with value: 0.5595644894807477 and parameters: {'n_estimators': 1339, 'max_depth': 3, 'learning_rate': 0.02753827537096348, 'subsample': 0.8841069619991342, 'colsample_bytree': 0.5403382523717538, 'min_child_weight': 1, 'gamma': 0.04709833856624101, 'reg_alpha': 0.5, 'reg_lambda': 0.004743220125238651}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:41,984] Trial 58 finished with value: 0.5595644894807477 and parameters: {'n_estimators': 1339, 'max_depth': 3, 'learning_rate': 0.02753827537096348, 'subsample': 0.8841069619991342, 'colsample_bytree': 0.5403382523717538, 'min_child_weight': 1, 'gamma': 0.04709833856624101, 'reg_alpha': 0.5, 'reg_lambda': 0.004743220125238651}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:42,278] Trial 43 finished with value: 0.5599020972950846 and parameters: {'n_estimators': 1339, 'max_depth': 3, 'learning_rate': 0.02753493187547608, 'subsample': 0.884155768323781, 'colsample_bytree': 0.540241878323324, 'min_child_weight': 1, 'gamma': 0.04715800979731199, 'reg_alpha': 0.5, 'reg_lambda': 0.004728198560407319}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:42,423] Trial 63 finished with value: 0.5595644894807477 and parameters: {'n_estimators': 1339, 'max_depth': 3, 'learning_rate': 0.02753827537096348, 'subsample': 0.8841069619991342, 'colsample_bytree': 0.5403382523717538, 'min_child_weight': 1, 'gamma': 0.04709833856624101, 'reg_alpha': 0.5, 'reg_lambda': 0.004743220125238651}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:42,611] Trial 49 finished with value: 0.5595644894807477 and parameters: {'n_estimators': 1339, 'max_depth': 3, 'learning_rate': 0.02753827537096348, 'subsample': 0.8841069619991342, 'colsample_bytree': 0.5403382523717538, 'min_child_weight': 1, 'gamma': 0.04709833856624101, 'reg_alpha': 0.5, 'reg_lambda': 0.004743220125238651}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:49,986] Trial 64 finished with value: 0.5643966371022244 and parameters: {'n_estimators': 367, 'max_depth': 3, 'learning_rate': 0.025020915870114124, 'subsample': 0.8331736356493311, 'colsample_bytree': 0.6875240947025575, 'min_child_weight': 1, 'gamma': 0.00011703638765995459, 'reg_alpha': 0.020008622960180623, 'reg_lambda': 0.0013075879107373053}. Best is trial 25 with value: 0.5166598487363987.
[I 2024-12-04 14:51:52,091] Trial 66 finished with value: 0.5108689214846374 and parameters: {'n_estimators': 1371, 'max_depth': 8, 'learning_rate': 0.010000000000000004, 'subsample': 0.8912103912173237, 'colsample_bytree': 0.6491067069963856, 'min_child_weight': 1, 'gamma': 0.0004617744488454066, 'reg_alpha': 0.006160862474806773, 'reg_lambda': 0.10427511222618617}. Best is trial 66 with value: 0.5108689214846374.
[I 2024-12-04 14:51:54,918] Trial 65 finished with value: 0.5325063315532069 and parameters: {'n_estimators': 1232, 'max_depth': 6, 'learning_rate': 0.011365481360186872, 'subsample': 0.7901891820654168, 'colsample_bytree': 0.6557671115858423, 'min_child_weight': 1, 'gamma': 0.0001669509396664691, 'reg_alpha': 0.00826693289465154, 'reg_lambda': 0.2733424869677104}. Best is trial 66 with value: 0.5108689214846374.
[I 2024-12-04 14:51:59,932] Trial 68 finished with value: 0.5325415823614522 and parameters: {'n_estimators': 1045, 'max_depth': 5, 'learning_rate': 0.010000000000000004, 'subsample': 0.8762795600519282, 'colsample_bytree': 0.5631638330388488, 'min_child_weight': 1, 'gamma': 0.0026272636684805425, 'reg_alpha': 0.0032169270690179832, 'reg_lambda': 0.002151783964250076}. Best is trial 66 with value: 0.5108689214846374.
[I 2024-12-04 14:52:01,155] Trial 67 finished with value: 0.5219733651545349 and parameters: {'n_estimators': 1110, 'max_depth': 6, 'learning_rate': 0.010000000000000004, 'subsample': 0.8875746164831458, 'colsample_bytree': 0.6134451621240491, 'min_child_weight': 1, 'gamma': 0.0005376951573544671, 'reg_alpha': 0.004261135981803467, 'reg_lambda': 0.01700306452489213}. Best is trial 66 with value: 0.5108689214846374.
[I 2024-12-04 14:52:02,835] Trial 69 finished with value: 0.5221442610794607 and parameters: {'n_estimators': 1110, 'max_depth': 6, 'learning_rate': 0.010000000000000004, 'subsample': 0.8873091859226402, 'colsample_bytree': 0.6136406613810239, 'min_child_weight': 1, 'gamma': 0.000539447120995473, 'reg_alpha': 0.0042678147588891, 'reg_lambda': 0.017136678577210886}. Best is trial 66 with value: 0.5108689214846374.
[I 2024-12-04 14:52:04,442] Trial 72 finished with value: 0.5202328547392349 and parameters: {'n_estimators': 1106, 'max_depth': 6, 'learning_rate': 0.010000000000000004, 'subsample': 0.8877906742350377, 'colsample_bytree': 0.6165375317308496, 'min_child_weight': 1, 'gamma': 0.0005335787202650793, 'reg_alpha': 0.0042538030627943145, 'reg_lambda': 0.019972286443843575}. Best is trial 66 with value: 0.5108689214846374.
[I 2024-12-04 14:52:04,984] Trial 71 finished with value: 0.5220019402041892 and parameters: {'n_estimators': 1112, 'max_depth': 6, 'learning_rate': 0.010000000000000004, 'subsample': 0.8872617494900312, 'colsample_bytree': 0.6124875774481019, 'min_child_weight': 1, 'gamma': 0.000547125052068931, 'reg_alpha': 0.004262039607095214, 'reg_lambda': 0.015947626839872223}. Best is trial 66 with value: 0.5108689214846374.
[I 2024-12-04 14:52:05,777] Trial 77 finished with value: 0.534838350185653 and parameters: {'n_estimators': 1204, 'max_depth': 6, 'learning_rate': 0.08066162107626627, 'subsample': 0.838637260277272, 'colsample_bytree': 0.6386322916351511, 'min_child_weight': 1, 'gamma': 0.014927950000570518, 'reg_alpha': 0.006200974089073673, 'reg_lambda': 0.0002705011497400465}. Best is trial 66 with value: 0.5108689214846374.
[I 2024-12-04 14:52:08,675] Trial 79 finished with value: 0.531074280227872 and parameters: {'n_estimators': 1203, 'max_depth': 6, 'learning_rate': 0.08097671171218995, 'subsample': 0.8394381700526437, 'colsample_bytree': 0.6395268494632211, 'min_child_weight': 1, 'gamma': 0.014783156366443092, 'reg_alpha': 0.006098050151365682, 'reg_lambda': 0.0002839267487986852}. Best is trial 66 with value: 0.5108689214846374.
[I 2024-12-04 14:52:09,293] Trial 70 finished with value: 0.5204689897560937 and parameters: {'n_estimators': 1115, 'max_depth': 6, 'learning_rate': 0.010000000000000004, 'subsample': 0.8868352034248572, 'colsample_bytree': 0.609704713629377, 'min_child_weight': 1, 'gamma': 0.0005666607153913343, 'reg_alpha': 0.004246932238089492, 'reg_lambda': 0.014171828454789537}. Best is trial 66 with value: 0.5108689214846374.
[I 2024-12-04 14:52:14,297] Trial 76 finished with value: 0.5465770387508623 and parameters: {'n_estimators': 1204, 'max_depth': 6, 'learning_rate': 0.08059844268912496, 'subsample': 0.8381311661842799, 'colsample_bytree': 0.6383696243094642, 'min_child_weight': 1, 'gamma': 0.014927284299268134, 'reg_alpha': 0.0061271817034868475, 'reg_lambda': 0.0002744213357923313}. Best is trial 66 with value: 0.5108689214846374.
[I 2024-12-04 14:52:15,153] Trial 75 finished with value: 0.5431596157448081 and parameters: {'n_estimators': 1204, 'max_depth': 6, 'learning_rate': 0.08086496443306862, 'subsample': 0.8379554244264138, 'colsample_bytree': 0.6385297518921954, 'min_child_weight': 1, 'gamma': 0.014961848225281217, 'reg_alpha': 0.006122671082557908, 'reg_lambda': 0.00027339231273187595}. Best is trial 66 with value: 0.5108689214846374.
[I 2024-12-04 14:52:15,856] Trial 81 finished with value: 0.545407983794591 and parameters: {'n_estimators': 1204, 'max_depth': 6, 'learning_rate': 0.08069167727444242, 'subsample': 0.8379610593839001, 'colsample_bytree': 0.6387135867401246, 'min_child_weight': 1, 'gamma': 0.015003248446529428, 'reg_alpha': 0.006146432477532325, 'reg_lambda': 0.0002768979680545449}. Best is trial 66 with value: 0.5108689214846374.
[W 2024-12-04 14:52:16,152] Trial 80 failed with parameters: {} because of the following error: StorageInternalError('An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. ').
Traceback (most recent call last):
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 81, in _create_scoped_session
    session.commit()
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4488, in _flush
    transaction.rollback(_capture_exception=True)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO trial_params (trial_id, param_name, param_value, distribution_json) VALUES (?, ?, ?, ?)]
[parameters: (81, 'n_estimators', 1203.0, '{"name": "IntDistribution", "attributes": {"log": false, "step": 1, "low": 100, "high": 1500}}')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "/zhome/b1/0/88900/Documents/fair_gc/src/optims.py", line 242, in objective
    params = {
  File "/zhome/b1/0/88900/Documents/fair_gc/src/optims.py", line 243, in <dictcomp>
    name: suggest_fn(trial, name)
  File "/zhome/b1/0/88900/Documents/fair_gc/src/optims.py", line 164, in <lambda>
    return lambda trial, name: trial.suggest_int(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/_convert_positional_args.py", line 83, in converter_wrapper
    return func(**kwargs)  # type: ignore[call-arg]
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/trial/_trial.py", line 324, in suggest_int
    suggested_value = int(self._suggest(name, distribution))
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/trial/_trial.py", line 637, in _suggest
    storage.set_trial_param(trial_id, name, param_value_in_internal_repr, distribution)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_cached_storage.py", line 171, in set_trial_param
    self._backend.set_trial_param(trial_id, param_name, param_value_internal, distribution)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 585, in set_trial_param
    self._set_trial_param_without_commit(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 98, in _create_scoped_session
    raise optuna.exceptions.StorageInternalError(message) from e
optuna.exceptions.StorageInternalError: An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. 
[W 2024-12-04 14:52:16,227] Trial 80 failed with value None.
[I 2024-12-04 14:52:16,427] Trial 84 finished with value: 0.5383843052653917 and parameters: {'n_estimators': 1204, 'max_depth': 6, 'learning_rate': 0.0809298081326266, 'subsample': 0.8380799758706066, 'colsample_bytree': 0.6384011099090818, 'min_child_weight': 1, 'gamma': 0.014956581114938625, 'reg_alpha': 0.0061266643031020794, 'reg_lambda': 0.00027205403337564923}. Best is trial 66 with value: 0.5108689214846374.
[I 2024-12-04 14:52:16,770] Trial 78 finished with value: 0.5456254504896151 and parameters: {'n_estimators': 1204, 'max_depth': 6, 'learning_rate': 0.08086591531275583, 'subsample': 0.8378406774180267, 'colsample_bytree': 0.6385271473755768, 'min_child_weight': 1, 'gamma': 0.015002446111200902, 'reg_alpha': 0.006116274192475749, 'reg_lambda': 0.00027411398153537314}. Best is trial 66 with value: 0.5108689214846374.
[I 2024-12-04 14:52:16,991] Trial 92 finished with value: 0.545002735625059 and parameters: {'n_estimators': 1204, 'max_depth': 6, 'learning_rate': 0.08093655847170307, 'subsample': 0.8383031568754664, 'colsample_bytree': 0.6386291849023058, 'min_child_weight': 1, 'gamma': 0.014956763286823334, 'reg_alpha': 0.006139290817161216, 'reg_lambda': 0.0002762803923873778}. Best is trial 66 with value: 0.5108689214846374.
[W 2024-12-04 14:52:17,216] Trial 83 failed with parameters: {'n_estimators': 1205} because of the following error: StorageInternalError('An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. ').
Traceback (most recent call last):
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 81, in _create_scoped_session
    session.commit()
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4488, in _flush
    transaction.rollback(_capture_exception=True)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO trial_params (trial_id, param_name, param_value, distribution_json) VALUES (?, ?, ?, ?)]
[parameters: (84, 'max_depth', 6.0, '{"name": "IntDistribution", "attributes": {"log": false, "step": 1, "low": 3, "high": 12}}')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "/zhome/b1/0/88900/Documents/fair_gc/src/optims.py", line 242, in objective
    params = {
  File "/zhome/b1/0/88900/Documents/fair_gc/src/optims.py", line 243, in <dictcomp>
    name: suggest_fn(trial, name)
  File "/zhome/b1/0/88900/Documents/fair_gc/src/optims.py", line 164, in <lambda>
    return lambda trial, name: trial.suggest_int(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/_convert_positional_args.py", line 83, in converter_wrapper
    return func(**kwargs)  # type: ignore[call-arg]
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/trial/_trial.py", line 324, in suggest_int
    suggested_value = int(self._suggest(name, distribution))
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/trial/_trial.py", line 637, in _suggest
    storage.set_trial_param(trial_id, name, param_value_in_internal_repr, distribution)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_cached_storage.py", line 171, in set_trial_param
    self._backend.set_trial_param(trial_id, param_name, param_value_internal, distribution)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 585, in set_trial_param
    self._set_trial_param_without_commit(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 98, in _create_scoped_session
    raise optuna.exceptions.StorageInternalError(message) from e
optuna.exceptions.StorageInternalError: An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. 
[W 2024-12-04 14:52:17,230] Trial 83 failed with value None.
[W 2024-12-04 14:52:17,270] Trial 73 failed with parameters: {'n_estimators': 1204, 'max_depth': 6, 'learning_rate': 0.08075191844441468, 'subsample': 0.8383359567199402, 'colsample_bytree': 0.6384368330656276, 'min_child_weight': 1, 'gamma': 0.014847913336177673, 'reg_alpha': 0.0061435984187893315} because of the following error: StorageInternalError('An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. ').
Traceback (most recent call last):
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 81, in _create_scoped_session
    session.commit()
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4488, in _flush
    transaction.rollback(_capture_exception=True)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO trial_params (trial_id, param_name, param_value, distribution_json) VALUES (?, ?, ?, ?)]
[parameters: (74, 'reg_lambda', 0.0002762878969870141, '{"name": "FloatDistribution", "attributes": {"step": null, "low": 1e-05, "high": 0.5, "log": true}}')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "/zhome/b1/0/88900/Documents/fair_gc/src/optims.py", line 242, in objective
    params = {
  File "/zhome/b1/0/88900/Documents/fair_gc/src/optims.py", line 243, in <dictcomp>
    name: suggest_fn(trial, name)
  File "/zhome/b1/0/88900/Documents/fair_gc/src/optims.py", line 157, in <lambda>
    return lambda trial, name: trial.suggest_float(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/trial/_trial.py", line 161, in suggest_float
    suggested_value = self._suggest(name, distribution)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/trial/_trial.py", line 637, in _suggest
    storage.set_trial_param(trial_id, name, param_value_in_internal_repr, distribution)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_cached_storage.py", line 171, in set_trial_param
    self._backend.set_trial_param(trial_id, param_name, param_value_internal, distribution)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 585, in set_trial_param
    self._set_trial_param_without_commit(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 98, in _create_scoped_session
    raise optuna.exceptions.StorageInternalError(message) from e
optuna.exceptions.StorageInternalError: An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. 
[W 2024-12-04 14:52:17,276] Trial 73 failed with value None.
[I 2024-12-04 14:52:17,842] Trial 94 finished with value: 0.547278676807896 and parameters: {'n_estimators': 1204, 'max_depth': 6, 'learning_rate': 0.0809723111226909, 'subsample': 0.8379907297581928, 'colsample_bytree': 0.6382846078708975, 'min_child_weight': 1, 'gamma': 0.014826836458573288, 'reg_alpha': 0.006150113832020977, 'reg_lambda': 0.00027366493912109655}. Best is trial 66 with value: 0.5108689214846374.
[I 2024-12-04 14:52:17,844] Trial 89 finished with value: 0.5356213820364313 and parameters: {'n_estimators': 1204, 'max_depth': 6, 'learning_rate': 0.08108049360517185, 'subsample': 0.8382240057270507, 'colsample_bytree': 0.6385296315609721, 'min_child_weight': 1, 'gamma': 0.014847008353950138, 'reg_alpha': 0.006136275776030667, 'reg_lambda': 0.0002743771170004474}. Best is trial 66 with value: 0.5108689214846374.
[I 2024-12-04 14:52:18,024] Trial 95 finished with value: 0.5444477655981036 and parameters: {'n_estimators': 1204, 'max_depth': 6, 'learning_rate': 0.08048227001955542, 'subsample': 0.8383634737692189, 'colsample_bytree': 0.6385789258356647, 'min_child_weight': 1, 'gamma': 0.014987591486510438, 'reg_alpha': 0.0061780419589999155, 'reg_lambda': 0.0002728588860938107}. Best is trial 66 with value: 0.5108689214846374.
[W 2024-12-04 14:52:18,215] Trial 82 failed with parameters: {'n_estimators': 1204, 'max_depth': 6, 'learning_rate': 0.08103596539506308, 'subsample': 0.8382349983786929, 'colsample_bytree': 0.6385495576182725} because of the following error: StorageInternalError('An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. ').
Traceback (most recent call last):
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 81, in _create_scoped_session
    session.commit()
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4488, in _flush
    transaction.rollback(_capture_exception=True)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO trial_params (trial_id, param_name, param_value, distribution_json) VALUES (?, ?, ?, ?)]
[parameters: (83, 'min_child_weight', 1.0, '{"name": "IntDistribution", "attributes": {"log": false, "step": 1, "low": 1, "high": 5}}')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "/zhome/b1/0/88900/Documents/fair_gc/src/optims.py", line 242, in objective
    params = {
  File "/zhome/b1/0/88900/Documents/fair_gc/src/optims.py", line 243, in <dictcomp>
    name: suggest_fn(trial, name)
  File "/zhome/b1/0/88900/Documents/fair_gc/src/optims.py", line 164, in <lambda>
    return lambda trial, name: trial.suggest_int(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/_convert_positional_args.py", line 83, in converter_wrapper
    return func(**kwargs)  # type: ignore[call-arg]
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/trial/_trial.py", line 324, in suggest_int
    suggested_value = int(self._suggest(name, distribution))
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/trial/_trial.py", line 637, in _suggest
    storage.set_trial_param(trial_id, name, param_value_in_internal_repr, distribution)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_cached_storage.py", line 171, in set_trial_param
    self._backend.set_trial_param(trial_id, param_name, param_value_internal, distribution)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 585, in set_trial_param
    self._set_trial_param_without_commit(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 98, in _create_scoped_session
    raise optuna.exceptions.StorageInternalError(message) from e
optuna.exceptions.StorageInternalError: An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. 
[W 2024-12-04 14:52:18,234] Trial 82 failed with value None.
[I 2024-12-04 14:52:18,852] Trial 85 finished with value: 0.5460748866288836 and parameters: {'n_estimators': 1204, 'max_depth': 6, 'learning_rate': 0.08093590869294437, 'subsample': 0.8379395524238756, 'colsample_bytree': 0.638343966158958, 'min_child_weight': 1, 'gamma': 0.014863652098612037, 'reg_alpha': 0.006152343542565313, 'reg_lambda': 0.0002744328045185123}. Best is trial 66 with value: 0.5108689214846374.
[I 2024-12-04 14:52:18,986] Trial 96 finished with value: 0.5240602682043941 and parameters: {'n_estimators': 1470, 'max_depth': 6, 'learning_rate': 0.06620909472515754, 'subsample': 0.8670025939241872, 'colsample_bytree': 0.6318123679052245, 'min_child_weight': 1, 'gamma': 0.017273697034983975, 'reg_alpha': 0.00189324178933664, 'reg_lambda': 0.00026821485144183605}. Best is trial 66 with value: 0.5108689214846374.
[I 2024-12-04 14:52:19,042] Trial 74 finished with value: 0.5438203873683911 and parameters: {'n_estimators': 1204, 'max_depth': 6, 'learning_rate': 0.08095572722147051, 'subsample': 0.8382581234299136, 'colsample_bytree': 0.6386257891350483, 'min_child_weight': 1, 'gamma': 0.014945881662097501, 'reg_alpha': 0.006143990926163261, 'reg_lambda': 0.0002760605698742718}. Best is trial 66 with value: 0.5108689214846374.
[W 2024-12-04 14:52:19,126] Trial 87 failed with parameters: {'n_estimators': 1204, 'max_depth': 6, 'learning_rate': 0.08088276895759484, 'subsample': 0.8383687713316385, 'colsample_bytree': 0.6386454274617995, 'min_child_weight': 1} because of the following error: StorageInternalError('An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. ').
Traceback (most recent call last):
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 81, in _create_scoped_session
    session.commit()
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4488, in _flush
    transaction.rollback(_capture_exception=True)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO trial_params (trial_id, param_name, param_value, distribution_json) VALUES (?, ?, ?, ?)]
[parameters: (88, 'gamma', 0.014982427637281897, '{"name": "FloatDistribution", "attributes": {"step": null, "low": 1e-05, "high": 0.5, "log": true}}')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "/zhome/b1/0/88900/Documents/fair_gc/src/optims.py", line 242, in objective
    params = {
  File "/zhome/b1/0/88900/Documents/fair_gc/src/optims.py", line 243, in <dictcomp>
    name: suggest_fn(trial, name)
  File "/zhome/b1/0/88900/Documents/fair_gc/src/optims.py", line 157, in <lambda>
    return lambda trial, name: trial.suggest_float(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/trial/_trial.py", line 161, in suggest_float
    suggested_value = self._suggest(name, distribution)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/trial/_trial.py", line 637, in _suggest
    storage.set_trial_param(trial_id, name, param_value_in_internal_repr, distribution)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_cached_storage.py", line 171, in set_trial_param
    self._backend.set_trial_param(trial_id, param_name, param_value_internal, distribution)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 585, in set_trial_param
    self._set_trial_param_without_commit(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 98, in _create_scoped_session
    raise optuna.exceptions.StorageInternalError(message) from e
optuna.exceptions.StorageInternalError: An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. 
[W 2024-12-04 14:52:19,130] Trial 87 failed with value None.
[I 2024-12-04 14:52:19,507] Trial 88 finished with value: 0.5400330148702871 and parameters: {'n_estimators': 1204, 'max_depth': 6, 'learning_rate': 0.08089346630484727, 'subsample': 0.8380620794943726, 'colsample_bytree': 0.6384414188746727, 'min_child_weight': 1, 'gamma': 0.014953307768201494, 'reg_alpha': 0.0061321721026849655, 'reg_lambda': 0.0002727016136016322}. Best is trial 66 with value: 0.5108689214846374.
[I 2024-12-04 14:52:19,587] Trial 90 finished with value: 0.5417107769915919 and parameters: {'n_estimators': 1204, 'max_depth': 6, 'learning_rate': 0.08100551166506113, 'subsample': 0.838210384186981, 'colsample_bytree': 0.6385709558106402, 'min_child_weight': 1, 'gamma': 0.014900594307262423, 'reg_alpha': 0.006149809200124589, 'reg_lambda': 0.0002753170618511291}. Best is trial 66 with value: 0.5108689214846374.
[I 2024-12-04 14:52:19,874] Trial 93 finished with value: 0.5475272997686781 and parameters: {'n_estimators': 1204, 'max_depth': 6, 'learning_rate': 0.08089503522577164, 'subsample': 0.8383779700018126, 'colsample_bytree': 0.6386269084278526, 'min_child_weight': 1, 'gamma': 0.014968112776824492, 'reg_alpha': 0.006126772958842007, 'reg_lambda': 0.00027667763504264805}. Best is trial 66 with value: 0.5108689214846374.
[I 2024-12-04 14:52:21,159] Trial 91 finished with value: 0.5419674191275907 and parameters: {'n_estimators': 1204, 'max_depth': 6, 'learning_rate': 0.08101150844131676, 'subsample': 0.8382128882050031, 'colsample_bytree': 0.6385659744110732, 'min_child_weight': 1, 'gamma': 0.014896955482618606, 'reg_alpha': 0.006148633801233649, 'reg_lambda': 0.0002752481424128301}. Best is trial 66 with value: 0.5108689214846374.
[I 2024-12-04 14:52:21,515] Trial 100 finished with value: 0.506446217183912 and parameters: {'n_estimators': 1500, 'max_depth': 8, 'learning_rate': 0.02639348087190382, 'subsample': 0.9708272157528812, 'colsample_bytree': 0.6397778562137394, 'min_child_weight': 1, 'gamma': 0.02046775311208712, 'reg_alpha': 0.00032309599925866124, 'reg_lambda': 0.0048338271568277216}. Best is trial 100 with value: 0.506446217183912.
[I 2024-12-04 14:52:21,724] Trial 97 finished with value: 0.5096208480030228 and parameters: {'n_estimators': 1500, 'max_depth': 8, 'learning_rate': 0.028852813688786404, 'subsample': 0.9175131915744748, 'colsample_bytree': 0.6244468311744377, 'min_child_weight': 1, 'gamma': 0.021362124043285424, 'reg_alpha': 0.0004344649460160456, 'reg_lambda': 0.008164104278110372}. Best is trial 100 with value: 0.506446217183912.
[I 2024-12-04 14:52:21,840] Trial 86 finished with value: 0.5424384794315431 and parameters: {'n_estimators': 1204, 'max_depth': 6, 'learning_rate': 0.08088497753071777, 'subsample': 0.8380316870429674, 'colsample_bytree': 0.6384630478129902, 'min_child_weight': 1, 'gamma': 0.014962764633439905, 'reg_alpha': 0.0061323272816947196, 'reg_lambda': 0.0002729267095767354}. Best is trial 100 with value: 0.506446217183912.
[I 2024-12-04 14:52:21,884] Trial 102 finished with value: 0.520300402509042 and parameters: {'n_estimators': 1500, 'max_depth': 9, 'learning_rate': 0.011312630196780018, 'subsample': 1.0, 'colsample_bytree': 0.6752234300140938, 'min_child_weight': 1, 'gamma': 0.010017201273962923, 'reg_alpha': 0.0008352593283901423, 'reg_lambda': 0.2647390344644798}. Best is trial 99 with value: 0.5032747006412913.
[I 2024-12-04 14:52:21,894] Trial 99 finished with value: 0.5032747006412913 and parameters: {'n_estimators': 1500, 'max_depth': 8, 'learning_rate': 0.026593264486094833, 'subsample': 0.9593317900578658, 'colsample_bytree': 0.637378014898295, 'min_child_weight': 1, 'gamma': 0.02092795544092011, 'reg_alpha': 0.0003344439141946121, 'reg_lambda': 0.006353352094085346}. Best is trial 99 with value: 0.5032747006412913.
[I 2024-12-04 14:52:21,993] Trial 101 finished with value: 0.5009639384899539 and parameters: {'n_estimators': 1500, 'max_depth': 8, 'learning_rate': 0.022997874465214858, 'subsample': 0.9948841494929199, 'colsample_bytree': 0.6533921628580807, 'min_child_weight': 1, 'gamma': 0.0160167382131862, 'reg_alpha': 0.0003272279205422096, 'reg_lambda': 0.017740671935282636}. Best is trial 101 with value: 0.5009639384899539.
[I 2024-12-04 14:52:22,146] Trial 98 finished with value: 0.5021244672585622 and parameters: {'n_estimators': 1500, 'max_depth': 8, 'learning_rate': 0.027387996336445137, 'subsample': 0.9582345569207932, 'colsample_bytree': 0.6407032138259958, 'min_child_weight': 1, 'gamma': 0.021901456884221352, 'reg_alpha': 0.0004523583936505282, 'reg_lambda': 0.0069287744718926824}. Best is trial 101 with value: 0.5009639384899539.
[I 2024-12-04 14:52:22,378] Trial 103 finished with value: 0.521232900252791 and parameters: {'n_estimators': 1500, 'max_depth': 9, 'learning_rate': 0.011325951879134882, 'subsample': 1.0, 'colsample_bytree': 0.6753434520211866, 'min_child_weight': 1, 'gamma': 0.010011471502436257, 'reg_alpha': 0.0008437453718694654, 'reg_lambda': 0.2645740934132581}. Best is trial 101 with value: 0.5009639384899539.
[I 2024-12-04 14:52:24,075] Trial 104 finished with value: 0.5129520955146557 and parameters: {'n_estimators': 1500, 'max_depth': 9, 'learning_rate': 0.013204804909881247, 'subsample': 1.0, 'colsample_bytree': 0.6683776663942522, 'min_child_weight': 1, 'gamma': 0.009050678581567058, 'reg_alpha': 0.0004848020395686258, 'reg_lambda': 0.08500201651693957}. Best is trial 101 with value: 0.5009639384899539.
[I 2024-12-04 14:52:25,175] Trial 106 finished with value: 0.5130522230699073 and parameters: {'n_estimators': 1500, 'max_depth': 10, 'learning_rate': 0.013018101642285264, 'subsample': 1.0, 'colsample_bytree': 0.6764301157211008, 'min_child_weight': 1, 'gamma': 0.013507137819924136, 'reg_alpha': 0.0005860812343768942, 'reg_lambda': 0.45210062028381054}. Best is trial 101 with value: 0.5009639384899539.
[I 2024-12-04 14:52:25,587] Trial 105 finished with value: 0.512819418991334 and parameters: {'n_estimators': 1500, 'max_depth': 10, 'learning_rate': 0.013035749976692339, 'subsample': 1.0, 'colsample_bytree': 0.6763166480125655, 'min_child_weight': 1, 'gamma': 0.013456650604701628, 'reg_alpha': 0.000585524648909373, 'reg_lambda': 0.454010539683515}. Best is trial 101 with value: 0.5009639384899539.
[I 2024-12-04 14:52:25,839] Trial 108 finished with value: 0.5127917482603842 and parameters: {'n_estimators': 1500, 'max_depth': 11, 'learning_rate': 0.011179122179373231, 'subsample': 1.0, 'colsample_bytree': 0.6784468702697841, 'min_child_weight': 1, 'gamma': 0.016948478237989673, 'reg_alpha': 0.0005922267222238474, 'reg_lambda': 0.4999999999999991}. Best is trial 101 with value: 0.5009639384899539.
[I 2024-12-04 14:52:26,008] Trial 109 finished with value: 0.5104245836072459 and parameters: {'n_estimators': 1500, 'max_depth': 11, 'learning_rate': 0.010896853896138554, 'subsample': 1.0, 'colsample_bytree': 0.6781939343506747, 'min_child_weight': 1, 'gamma': 0.01772204283080389, 'reg_alpha': 0.0005719120795149433, 'reg_lambda': 0.5}. Best is trial 101 with value: 0.5009639384899539.
[I 2024-12-04 14:52:26,122] Trial 107 finished with value: 0.5121156460323075 and parameters: {'n_estimators': 1500, 'max_depth': 11, 'learning_rate': 0.011178092984802051, 'subsample': 1.0, 'colsample_bytree': 0.6784514148426193, 'min_child_weight': 1, 'gamma': 0.016953417895401328, 'reg_alpha': 0.0005923198760385766, 'reg_lambda': 0.4999999999999991}. Best is trial 101 with value: 0.5009639384899539.
Traceback (most recent call last):
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 81, in _create_scoped_session
    session.commit()
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4488, in _flush
    transaction.rollback(_capture_exception=True)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO trial_params (trial_id, param_name, param_value, distribution_json) VALUES (?, ?, ?, ?)]
[parameters: (81, 'n_estimators', 1203.0, '{"name": "IntDistribution", "attributes": {"log": false, "step": 1, "low": 100, "high": 1500}}')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/zhome/b1/0/88900/Documents/fair_gc/gc_ml.py", line 79, in <module>
    study, best_model = create_hyperparameter_optimizer(
  File "/zhome/b1/0/88900/Documents/fair_gc/src/optims.py", line 275, in create_hyperparameter_optimizer
    study.optimize(objective, n_trials=n_trials, n_jobs=n_jobs)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/study/study.py", line 475, in optimize
    _optimize(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/study/_optimize.py", line 100, in _optimize
    f.result()
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/study/_optimize.py", line 248, in _run_trial
    raise func_err
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "/zhome/b1/0/88900/Documents/fair_gc/src/optims.py", line 242, in objective
    params = {
  File "/zhome/b1/0/88900/Documents/fair_gc/src/optims.py", line 243, in <dictcomp>
    name: suggest_fn(trial, name)
  File "/zhome/b1/0/88900/Documents/fair_gc/src/optims.py", line 164, in <lambda>
    return lambda trial, name: trial.suggest_int(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/_convert_positional_args.py", line 83, in converter_wrapper
    return func(**kwargs)  # type: ignore[call-arg]
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/trial/_trial.py", line 324, in suggest_int
    suggested_value = int(self._suggest(name, distribution))
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/trial/_trial.py", line 637, in _suggest
    storage.set_trial_param(trial_id, name, param_value_in_internal_repr, distribution)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_cached_storage.py", line 171, in set_trial_param
    self._backend.set_trial_param(trial_id, param_name, param_value_internal, distribution)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 585, in set_trial_param
    self._set_trial_param_without_commit(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 98, in _create_scoped_session
    raise optuna.exceptions.StorageInternalError(message) from e
optuna.exceptions.StorageInternalError: An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. 
