Seed set to 42
Seed set to 42
[I 2024-12-25 11:55:19,407] A new study created in RDB with name: groupgat_Tc_groupgat
[W 2024-12-25 11:55:23,961] Trial 0 failed with parameters: {'L1_hidden_dim': 176, 'L1_layers_atom': 2, 'L1_layers_mol': 3, 'L1_dropout': 0.12691695814111842, 'L1_out_dim': 48, 'L2_hidden_dim': 128, 'L2_layers_atom': 2, 'L2_layers_mol': 1, 'L2_out_dim': 48, 'L2_dropout': 0.1941953498427031, 'L3_hidden_dim': 48, 'L3_layers_atom': 4, 'L3_layers_mol': 2, 'L3_out_dim': 80, 'L3_dropout': 0.28059886805484324, 'n_mlp_layers': 1, 'mlp_dim_0': 336, 'num_heads': 1, 'final_dropout': 0.16773059205561067, 'train_learning_rate': 0.0002568372379410149, 'train_lr_reduce': 0.6} because of the following error: RuntimeError('Parent directory work3/arnaou/checkpoints does not exist.').
Traceback (most recent call last):
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "/zhome/b1/0/88900/Documents/fair_gc/src/gnn_hyperopt.py", line 1096, in objective
    torch.save({
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/torch/serialization.py", line 618, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/torch/serialization.py", line 492, in _open_zipfile_writer
    return container(name_or_buffer)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/torch/serialization.py", line 463, in __init__
    super().__init__(torch._C.PyTorchFileWriter(self.name))
RuntimeError: Parent directory work3/arnaou/checkpoints does not exist.
[W 2024-12-25 11:55:23,971] Trial 2 failed with parameters: {'L1_hidden_dim': 96, 'L1_layers_atom': 1, 'L1_layers_mol': 1, 'L1_dropout': 0.1593966471890371, 'L1_out_dim': 64, 'L2_hidden_dim': 128, 'L2_layers_atom': 2, 'L2_layers_mol': 3, 'L2_out_dim': 96, 'L2_dropout': 0.10799475084185188, 'L3_hidden_dim': 96, 'L3_layers_atom': 2, 'L3_layers_mol': 1, 'L3_out_dim': 80, 'L3_dropout': 0.15003416984149862, 'n_mlp_layers': 3, 'mlp_dim_0': 400, 'mlp_dim_1': 176, 'mlp_dim_2': 504, 'num_heads': 2, 'final_dropout': 0.011564058452747794, 'train_learning_rate': 0.001572861939176697, 'train_lr_reduce': 0.6} because of the following error: RuntimeError('Parent directory work3/arnaou/checkpoints does not exist.').
Traceback (most recent call last):
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "/zhome/b1/0/88900/Documents/fair_gc/src/gnn_hyperopt.py", line 1096, in objective
    torch.save({
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/torch/serialization.py", line 618, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/torch/serialization.py", line 492, in _open_zipfile_writer
    return container(name_or_buffer)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/torch/serialization.py", line 463, in __init__
    super().__init__(torch._C.PyTorchFileWriter(self.name))
RuntimeError: Parent directory work3/arnaou/checkpoints does not exist.
[W 2024-12-25 11:55:23,975] Trial 0 failed with value None.
[W 2024-12-25 11:55:23,975] Trial 2 failed with value None.
[W 2024-12-25 11:55:24,007] Trial 1 failed with parameters: {'L1_hidden_dim': 96, 'L1_layers_atom': 1, 'L1_layers_mol': 4, 'L1_dropout': 0.23123992171994276, 'L1_out_dim': 48, 'L2_hidden_dim': 128, 'L2_layers_atom': 4, 'L2_layers_mol': 4, 'L2_out_dim': 32, 'L2_dropout': 0.1685933939328624, 'L3_hidden_dim': 112, 'L3_layers_atom': 4, 'L3_layers_mol': 1, 'L3_out_dim': 48, 'L3_dropout': 0.03959951581310632, 'n_mlp_layers': 2, 'mlp_dim_0': 392, 'mlp_dim_1': 432, 'num_heads': 2, 'final_dropout': 0.2781179979320778, 'train_learning_rate': 0.001040283981875348, 'train_lr_reduce': 0.6} because of the following error: RuntimeError('Parent directory work3/arnaou/checkpoints does not exist.').
Traceback (most recent call last):
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "/zhome/b1/0/88900/Documents/fair_gc/src/gnn_hyperopt.py", line 1096, in objective
    torch.save({
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/torch/serialization.py", line 618, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/torch/serialization.py", line 492, in _open_zipfile_writer
    return container(name_or_buffer)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/torch/serialization.py", line 463, in __init__
    super().__init__(torch._C.PyTorchFileWriter(self.name))
RuntimeError: Parent directory work3/arnaou/checkpoints does not exist.
[W 2024-12-25 11:55:24,007] Trial 1 failed with value None.
Traceback (most recent call last):
  File "/zhome/b1/0/88900/Documents/fair_gc/groupgat_hyperopt.py", line 115, in <module>
    study, best_model, train_params, model_config, best_model_params = groupgat_hyperparameter_optimizer(
  File "/zhome/b1/0/88900/Documents/fair_gc/src/gnn_hyperopt.py", line 1141, in groupgat_hyperparameter_optimizer
    study.optimize(objective, n_trials=n_trials, n_jobs=n_jobs)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/study/study.py", line 475, in optimize
    _optimize(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/study/_optimize.py", line 100, in _optimize
    f.result()
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/study/_optimize.py", line 248, in _run_trial
    raise func_err
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "/zhome/b1/0/88900/Documents/fair_gc/src/gnn_hyperopt.py", line 1096, in objective
    torch.save({
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/torch/serialization.py", line 618, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/torch/serialization.py", line 492, in _open_zipfile_writer
    return container(name_or_buffer)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/torch/serialization.py", line 463, in __init__
    super().__init__(torch._C.PyTorchFileWriter(self.name))
RuntimeError: Parent directory work3/arnaou/checkpoints does not exist.
